extends:
  - stylelint-config-standard-scss
  - ../.stylelintrc.yml

plugins:
  - stylelint-scss

overrides:
  - files:
    - src/components/billing/components/replenish-cards-list/components/replenish-card/styles.scss
    rules:
      'declaration-no-important':
        - null
