export {
  ApiPath,
  AuthApiPath,
  BillingApiPath,
  CategoriesApiPath,
  ChatsApiPath,
  CourseModulesApiPath,
  CoursesApiPath,
  GroupsApiPath,
  InterviewsApiPath,
  MentorsApiPath,
  TasksApiPath,
  UserDetailsApiPath,
  UsersApiPath,
} from 'guruhub-shared/common/enums/enums';
