extends:
  - ../.eslintrc.yml

settings:
  import/ignore:
    - "node_modules/react-native/index\\.js$"

overrides:
  - files:
      - env.enum.ts
    rules:
      import/no-named-as-default:
        - off
