type: object
properties:
  note:
    type: string
    required: true
    example: Example task note message
  status:
    type: string
    enum:
      - Uncompleted
      - Pending
      - Rejected
      - Completed
