export * as appActions from './app/actions';
export * as authActions from './auth/actions';
export * as courseActions from './course/actions';
export * as courseModuleActions from './course-module/actions';
export * as dashboardActions from './dashboard/actions';
export * as interviewActions from './interview/actions';
export * as uamActions from './uam/actions';
export * as uamConfigureGroupActions from './uam-configure-group/actions';
export * as userDetailsActions from './user-details/actions';
