enum ExceptionMessage {
  UNKNOWN_ERROR = 'Unknown error occurred.',
  BAD_CREDENTIALS = 'You have entered an invalid email or password.',
  UNAUTHORIZED_USER = 'Unauthorized user.',
  INVALID_GROUP_NAME = 'Group name is invalid.',
  INVALID_GROUP_PERMISSIONS = 'Group permissions are invalid.',
  INVALID_GROUP_USERS = 'Group users are invalid.',
  INVALID_GROUP_ID = 'Group id is invalid.',
  INVALID_TOKEN = 'Token is invalid.',
  INVALID_URL_HOST = 'URL is invalid. Only courses from Udemy are supported.',
  INVALID_COURSE_VENDOR = 'Course vendor is invalid.',
  INVALID_COURSE_CATEGORY = 'Course category is invalid.',
  UDEMY_SERVER_RETURNED_AN_INVALID_RESPONSE = 'Udemy server returned an invalid response.',
  COURSE_NOT_FOUND = 'Course not found.',
  COURSE_EXIST = 'Course already exists.',
  UNKNOWN_INTERVIEW_NOTE_AUTHOR = 'Unknown interview note author',
  PERMISSION_LACK = 'You do not have permission to access this resource.',
  STORAGE_NOT_FOUND = 'Storage was not found.',
  INVALID_USER_REQUEST = 'User request is invalid.',
  INTERVIEW_EXIST = 'Interview for this category was either passed or is in progress.',
  INTERVIEW_DOES_NOT_EXIST = 'Interview with that ID does not exist.',
  ALREADY_MENTOR_FOR_COURSE = 'You are already a mentor for this course.',
  ALREADY_HAVE_MENTOR_FOR_COURSE = 'You already have a mentor for this course.',
  INVALID_FILE_TYPE = 'The uploaded file has an invalid type. Only PNG, JPEG and SVG files can be uploaded.',
  TASK_DOES_NOT_EXIST = 'Task does not exist.',
  TASK_COMPLETED = 'Task is already completed and cannot be updated.',
  USER_DETAILS_NOT_FOUND = 'User was not found.',
  FILE_TOO_BIG = 'This file is too large to upload. The maximum supported file size is: 1MB',
  UNABLE_TO_PERFORM_BILLING_OPERATION = 'Unable to perform billing operation',
  NOT_ENOUGH_FUNDS_TO_WITHDRAW = 'You do not have minimal sum of funds (1$) to withdraw.',
  USER_CAN_NOT_BE_DELETED = 'This user is forbidden to delete',
  MENTOR_CAN_NOT_BE_DELETED = 'This user is forbidden to delete because he is a mentor.',
  MENTEE_CAN_NOT_BE_DELETED = 'This user is forbidden to delete because he is a mentee.',
  INTERVIEWEE_CAN_NOT_BE_DELETED = 'This user is forbidden to delete because he has interviews.',
  PROTECTED_GROUP_UPDATE = 'This group is protected and cannot be updated.',
  PROTECTED_GROUP_DELETE = 'This group is protected and cannot be deleted.',
}
export { ExceptionMessage };
