enum ExceptionMessage {
  UNKNOWN_ERROR = 'Unknown error occurred.',
  BAD_CREDENTIALS = 'You have entered an invalid email or password.',
  UNAUTHORIZED_USER = 'Unauthorized user.',
  INVALID_COURSE_VENDOR = 'Course vendor is invalid.',
  INVALID_COURSE_CATEGORY = 'Course category is invalid.',
  INVALID_GROUP_NAME = 'Group name is invalid.',
  INVALID_GROUP_PERMISSIONS = 'Group permissions are invalid.',
  INVALID_GROUP_USERS = 'Group users are invalid.',
  INVALID_GROUP_ID = 'Group id is invalid.',
  INVALID_TOKEN = 'Token is invalid.',
  INVALID_URL_HOST = 'URL is invalid. Only courses from Udemy are supported.',
  UDEMY_SERVER_RETURNED_AN_INVALID_RESPONSE = 'Udemy server returned an invalid response',
  COURSE_NOT_FOUND = 'Course not found.',
  COURSE_EXIST = 'Course already exists.',
  UNKNOWN_INTERVIEW_NOTE_AUTHOR = 'Unknown interview note author',
  PERMISSION_LACK = 'You do not have permission to access this resource.',
  STORAGE_NOT_FOUND = 'Storage was not found',
}
export { ExceptionMessage };
