openapi: 3.0.0
info:
  title: GuruHub API
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  # Auth
  /auth/sign-up:
    $ref: './endpoints/auth/user-sign-up.yaml'
  /auth/sign-in:
    $ref: './endpoints/auth/user-sign-in.yaml'
  /auth/current-user:
    $ref: './endpoints/auth/current-user.yaml'
components:
  schemas:
    UserSignUpRequestDto:
      $ref: './schemas/auth/user-sign-up-request-dto.yaml'
    UserSignUpResponseDto:
      $ref: './schemas/auth/user-sign-up-response-dto.yaml'
    UserSignInRequestDto:
      $ref: './schemas/auth/user-sign-in-request-dto.yaml'
    UserSignInResponseDto:
      $ref: './schemas/auth/user-sign-in-response-dto.yaml'
    CurrentUserResponseDto:
      $ref: './schemas/auth/current-user-response-dto.yaml'
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
