openapi: 3.0.0
info:
  title: GuruHub API
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  # Auth
  /auth/sign-up:
    $ref: './endpoints/auth/user-sign-up.yaml'
  /auth/sign-in:
    $ref: './endpoints/auth/user-sign-in.yaml'
  # Users
  /users:
    $ref: './endpoints/users/users-get-all.yaml'
  /users/:id:
    $ref: './endpoints/users/user-delete.yaml'
components:
  schemas:
    UserSignUpRequestDto:
      $ref: './schemas/auth/user-sign-up-request-dto.yaml'
    UserSignUpResponseDto:
      $ref: './schemas/auth/user-sign-up-response-dto.yaml'
    UsersGetAllResponseDto:
      $ref: './schemas/users/users-get-all-response-dto.yaml'
    UserSignInRequestDto:
      $ref: './schemas/auth/user-sign-in-request-dto.yaml'
    UserSignInResponseDto:
      $ref: './schemas/auth/user-sign-in-response-dto.yaml'
    UserDeleteRequestDto:
      $ref: './schemas/users/user-delete-request-dto.yaml'
