name: Generate app schema

on:
  pull_request:
    paths:
      - docs/app-architecture/**/*.*

jobs:
  generate-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install OS dependencies
        run: sudo apt install graphviz

      - name: Install Python dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
        run: pip3 install diagrams

      - name: Generate diagram
        run: cd ./docs/app-architecture && python3 app-arch.py

      - name: Commit new diagram
        uses: EndBug/add-and-commit@v9
        with:
          add: './docs/app-architecture/*'
          message: '* application architecture schema'
